### ISSUE TITLE
Adjust public/private organization information: unauthenticated, authenticated, private

### ISSUE THREAD

**Issue by maxvisser** [teamforus/general#114]
@maxvisser commented on [Mon Jan 13 2020](https://github.com/teamforus/development/issues/310)

## Current situation

Currently we have two levels:
- level public -> everyone on the internet can see this contact information
- level private -> when logged in you can see this information

## Goal

Give providers/organization from granual control over their contact information:

- level public -> everyone on the internet can see this contact information
- level users only -> when logged in you can see this information
- level connections -> in some cases information is needed: product reservations, fund applications etc.

## proposed solution
change checkbox to a dropdown which is somewhat similar to how facebook does granual control. Automatically its on Users only. I would propose aswell to migrate everyone to users only. Make users only the default choice.

**Comment by maxvisser** [comment]
This needs design.
Signupflows need to be adjusted
edit organisation should be adjusted

**Comment by jamalv** [comment]
added to productboard: https://app.productboard.com/inbox/notes/17398937

**Comment by jamalv** [comment]
Just some thoughts:
I'd like to see if we can make a proposal with sensible defaults:
- Only showing contact details to logged in users instead of publicly on the internet might be good to avoid spam.
- If information is needed, probably we can inform users about this, but we can't really give an option because otherwise we'd break functionality.

In general I'd like to aim that we think up a good default policy, as choices like this are much harder to understand by the providers. We are in a much better position to come up with defaults that both protect privacy and are practical.

**Comment by maxvisser** [comment]
this might be a nice one for a first proposal for @RobinMeles as @maartenfv said during daily that he also wants more people to being able to make proposals.

**Comment by maxvisser** [comment]
moved this one to the inbox
