### ISSUE TITLE
Webshop Mobile menu

### ISSUE THREAD

**Issue by maxvisser** [teamforus/general#194]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
-

### Change description

On mobile we have a hamburger menu 
![image](https://user-images.githubusercontent.com/10818702/81561383-627c2480-9393-11ea-9ed0-4f111edc79a2.png)

Idea is to replace the hamburger menu with a bottom menu

![image](https://user-images.githubusercontent.com/10818702/81561443-7889e500-9393-11ea-8fe6-18d9a4b19cae.png)

![image](https://user-images.githubusercontent.com/10818702/81561456-7de72f80-9393-11ea-8675-588793efe203.png)

Figma:
https://www.figma.com/file/Z96JUSqKypvCPOYjWy5UbG/Mobile-webshop-menu?node-id=0%3A1

**Comment by jamalv** [comment]
@maxvisser I left a comment in figma about the call to action:

https://www.figma.com/file/Z96JUSqKypvCPOYjWy5UbG?node-id=1:70#32180943

**Comment by maxvisser** [comment]
whats in figma is almost done (thats the current status)

**Comment by jamalv** [comment]
As the concept/proposal is already clear and it's already in the development pipeline, maybe it is better for an actual designer to review it?  My main attention point: I think the icon is a bit weird for "applying" for something, also I think since it is a call to action (the main one) it should be differentiated more from the other buttons.
