### ISSUE TITLE
CR: drop support for iOS 10

### ISSUE THREAD

**Issue by maxvisser** [teamforus/general#283]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
-

### Change description
Some features like Dark Mode can only be used when you drop support for older iOS versions (these devices cannot use these new features). iOS 11 is compatible with these devices:
iPhone
iPhone X
iPhone 8
iPhone 8 Plus
iPhone 7
iPhone 7 Plus
iPhone 6s
iPhone 6s Plus
iPhone 6
iPhone 6 Plus
iPhone SE
iPhone 5s
iPad
12.9-inch iPad Pro (2nd generation)
12.9-inch iPad Pro (1st generation)
iPad Pro (10.5-inch)
iPad Pro (9.7-inch)
iPad Air 2
iPad Air
iPad (6th generation)
iPad (5th generation)
iPad mini 4
iPad mini 3
iPad mini 2
iPod touch
iPod touch (6th generation)

Some iPhones will still be using iOS 10 we need to analyze:
- How does dropping support affect our current users
- How big of a scope of user still run iOS 10
- Can we ask people to update their phone to latest iOS version

**Comment by jamalv** [comment]
Some adoption stats here: https://developer.apple.com/support/app-store/

**Comment by jamalv** [comment]
Sometimes people cannot update because they don't have enough storage available (for example). I would be a proponent of supporting old versions as long as possible. And even though dark mode is great, it's not really a strong enough reason to force people to upgrade imo :P

I do think (not completely sure) that you can download the last supported version from the app store if you have an old iOS. This means we can "drop" support without disabling people from using the version we added before updating.

**Comment by maxvisser** [comment]
I disagree with 'support as long as possible'; same as supporting an old browsers. Best described here:
https://medium.com/marino-software/why-you-should-stop-supporting-older-os-versions-ba55115dd16

**Comment by jamalv** [comment]
For iOS I think we can stop supporting when apple considers it "vintage" - the newest vintage iPhone is now the 5: https://support.apple.com/en-us/HT201624; which supports up to iOS 10.3.4 - it would be my preference to also support that.

**Comment by maxvisser** [comment]
Yes maybe we can define what 'supporting' means; As I see it we should test and ensure quality on these platforms (what we currently not always do)

**Comment by maxvisser** [comment]
Unassinged parties as it is currently not actively being worked on.
