### ISSUE TITLE
CR: Add target audience to offers.

### ISSUE THREAD

**Issue by maartenfv** [teamforus/general#287]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
- SDOA (oostgelre)

### Change description
SDOA wants to add target audience functionalities (doelgroepen) to the website.

More specifically they would like to see that we add target audience tags to the offers.

- Tags such as
  - Target age
  - Wheelchair accessible
  - Uniek sporten (https://www.unieksporten.nl/) 
  - etc. 

Example: ![image.png](https://images.zenhubusercontent.com/5e79d94fc5b97af9090e495c/8a9dc09d-6f3b-40f2-873d-33e2c83559a3)

These tags need to be searchable from a dropdown.

![image.png](https://images.zenhubusercontent.com/5e79d94fc5b97af9090e495c/55593851-7c98-4ca7-9020-9c03f686a944)![image.png](https://images.zenhubusercontent.com/5e79d94fc5b97af9090e495c/26a8eb5b-61b2-4c58-b343-2a18bad70ff4)

When a provider makes an offer they need to be able to add target audiences.

**These target audiences should have Icons.**

![image.png](https://images.zenhubusercontent.com/5e79d94fc5b97af9090e495c/65739996-191c-42fe-a330-c784b3defbe1)

**Comment by maxvisser** [comment]
who will create and manage these 'target' audiences

**Comment by maxvisser** [comment]
do we already have a list of possible audiences

**Comment by maxvisser** [comment]
lab issue is maybe related  https://github.com/teamforus/lab/issues/40

**Comment by maartenfv** [comment]
@maxvisser I see the relation with the lab issue. For now we can make a selection of target groups together with SDOA and Groningen. 

MVP
Providers will be able to add target groups to their offers
Requesters will be able to search for these targets groups.

**Comment by maartenfv** [comment]
@jamalv This might relate to Groningen as well? 

B3 Pashouder krijgt een gericht aanbod van aanbiedingen en gemeentelijke regelingen.
Gebaseerd op doelgroepen (o.b.v. leeftijd, product, kinderen, inkomen, etc.)

**Comment by maartenfv** [comment]
@maxvisser @jamalv I need to make a proposal for SDOA. How can we get to an MVP for this issue?

**Comment by maxvisser** [comment]
Not really the place to discuss stuff for specific clients @maartenfv Maybe open some deals/implementation issues?

I would start with defining which Audiences we should support.

Examples:

**Parental status **
No parent
Parents of Infants (0-1 years)
Parents of Toddlers (1-3 years)
Parents of Preschoolers (4-5 years)
Parents of Grade-Schoolers (6-12 years)
Parents of Teens (13-17 years)

**Marital Status**
In a Relationship
Married
Single

Aswell as currently product categories are not really fully implemented yet (we ask the provider to add a product to a specific category but we do not really fully utilize this yet. (would it not be better to finish that first?)

**Comment by jamalv** [comment]
## Using funds instead of tags

Target audiences are selected trough the _funds_ in the webshop. I would say the direction of satisfying this CR is to implement a fund overview in the webshop (overview of target audiences) and to maybe add the fund images to the product pages / overviews, also it should be possible to filter by fund (target audience).  If there is a fund for less-abled people that the provider has offers for, that can be shown (with the image / icon the sponsor chooses). 

It also is possible to filter by fund. We can also look into optimising this so that there are nicer paths for this for the user. 

**In conclusion:** this CR is ✅ if using **funds** to set this up is agreeable, this also fits our roadmap into making multiple funds better in the webshop. This data is already there, but we are not showing it to the user yet in this webshop. This means we will probably not (fully) satisfy the CR; but we will definitely make some steps in the right direction that is requested here, that will benefit all our users and will not increase complexity of the webshops by adding more data that we need to show.

@maartenfv do you think / can you check? if this direction would be satisfactory? I think the customer that requested this might not be familiar with the "funds" concept, it might be good to also start informing them on this part. If we will add tags, it will make the scope too big and not aligned with our roadmap, but if we focus on funds, this will be very nice to work on with a lot of overlap with other projects :)

**Comment by maartenfv** [comment]
I agree understand the concept of funds = targetgroup. However I do think that we can see these tags as a separate thing. 

Example: Person in a wheelchair. They just want to know what aanbod is relevant for them using Stadjserpas. Creating a whole new fund is conceptual a thing to do but in practice, it is much easier to allow the aanbieder to add wheelchair friendly tag to the offer. So that this aanvrager can see what is relevant for them.

**Comment by maartenfv** [comment]
Need to make a clear distinction between to problem the customer/stakeholder has and the vision that we have. A solution to the problem seems close.
