### ISSUE TITLE
CR: Adjust amount of budget voucher based on financial means

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/general#47]
Requested by: A Customer

### Change description
As a sponsor I would like to grant a citizen a voucher with a budget based on financial means (draagkracht)

**Comment by maxvisser** [comment]
@GerbenBosschieter / @jamalv you guys probably have more context around this CR. Could please refine the issue abit more. Currently I can't really see how big of a scope it is.

**Comment by maxvisser** [comment]
Spoke with jamal; I will the refine the CR myself more. Just need all context / mails;

**Comment by maxvisser** [comment]
Spoke with Gerben, he said this is on hold until there is more context (no more context than the first statement)

**Comment by jamalv** [comment]
My attempt to clarify the CR (might be a bit inaccurate):

A sponsor has a desire to be more flexible in the way that they set the budget of the fund. Right now there is a fund formula that dictates how much every requester gets. e.g. €300 per requester, based on an eligible key (record).

Some people have more income (e.g. 120% of the poverty line, instead of 110%)

The sponsor would like to allocate less to people with a higher income: so, €260 instead of €300 for example.

Right now this whole thing is being done trough "prevalidations" dashboard. We create the formula's directly in the database.

**Possible action** (related to their current way of working):
Change the fund formula for this fund, to be able to adjust the CSV file that is uploaded. This needs more configuration details around what is exactly needed and time from Max. I also think a bit of an impact analysis is needed to do this; is there a migration from the current situation to the desired situation? I think it will need maybe half a day from Max to do the impact analysis and make an improvement proposal, and then we also know if it is doable to implement this.

That is the short term solution > as a long term solution I think this should be much more transparant and user friendly / user configurable. I opened a CR for making this configurable by the user: https://github.com/teamforus/general/issues/280

**Comment by maxvisser** [comment]
I already did this; a few months back during an implementation of Forus. I found that when you want to start using the requester signupflow the criteria, a percentage of budget, is not possible. If you will never use the signupflow (steps created by the criteria) it is possible.

**Comment by maxvisser** [comment]
could be solved with #300

**Comment by jamalv** [comment]
@maxvisser @GerbenBosschieter I believe this is fixed now that they can directly assign a budget. Closing this. Please re-open if i'm wrong here :)
