### ISSUE TITLE
Landing / on boarding pages should be in design/context of the sponsor their webshop

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/general#492]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
- Sponsor

**Note:** This change was requested after acceptance testing with stakeholders of project 100

### Change description
- Stakeholder gaves us the feedback that the landing pages (so the pages where people can sign up and login as a employee or provider should be in the same design/context of the webshop.

### Reason:
- UX isn't matching expectations of user. It feels they open a page that doesn't belong to webshop/system

**Comment by maxvisser** [comment]
As we can already do this but it is not desireable to keep doing it; We can decide to copy css and create new landing page in style of Groningen. I rather deal with #71 Depends on priority on the issue and time thats needed for all must haves.

**Comment by SjoerdHilhorst** [comment]
https://github.com/teamforus/implementation/issues/508

**Comment by jamalv** [comment]
I agree with implementing https://github.com/teamforus/general/issues/71 as a fix for this I think that page.

@maxvisser what is the status of this issue? https://github.com/teamforus/general/issues/379 @SjoerdHilhorst wrote the code, is it part of .15? If so I think the task is quite simple:
Update the link in the footer to link to: https://forus.io/provider/sign-up

**Comment by maxvisser** [comment]
Its done but has some feature gaps which I can briefly show you. Maybe you can plan a short meeting when you have time?

**Comment by maartenfv** [comment]
@maxvisser What is the status on this issue?

**Comment by maartenfv** [comment]
I remember this as being a Must-have?

**Comment by maartenfv** [comment]
This issue needs to get a higher prio. The customer is very clear on the demand. We need to make a page for the sponsor and one for the provider. Each municipality needs webshop with a clear login flow for every role. Currently, https://inkomensondersteuning.nijmegen.nl/ has the right direction.

#71 is a temporary solution. During the next sprint 47+48 this needs to be worked on. This also means that #448 needs to go on hold.

**Comment by maartenfv** [comment]
During the sing=up there should be no mention of Forus.

**Comment by maartenfv** [comment]
![image.png](https://images.zenhubusercontent.com/5e79d94fc5b97af9090e495c/3cd35817-f153-4acd-bf74-075583780d7f)

**Comment by maxvisser** [comment]
On the strategy: Plan was to get rid of the landing pages of Nijmegen; as they are not well maintained and are not on a high standard. Also for a provider its weird that they enter the sign up flow and think that they chat with the Municipality while its actually Forus who responds. @GerbenBosschieter Is this a problem?

On how to fix this:
If we need footers / logos on signupflow and there is no other way; we could do this by implementing all webshops elements on the dashboard as well. (copying over the css from the webshop or creating a new design). There are no CMS for these pages; we could hardcode all texts. Before we could start development we need a clear goal:
where is a logo/styling needed? If possible I would strip as much as possible from the side of dashboards and implement as much of custization on the webshop side.

More important if we would go the direction of maintaining custom pages; I see of course alot of risks (as seen with the explanation text, you can't garantuee any quality on the content)

**Comment by jamalv** [comment]
Put a bit more thought into this after yesterday's brainstorm, and I think we can find a middle ground, like with the Me app page.

As discussed, there is a lot of complexity here with deployment of branded provider signupflow's since they and the dashboards are not part of the webshop codebase. (We'd need to add them +  deploy all the dashboards to the domain of the municipality to keep the session alive) - this leads to duplication of the dashboard codebases, more complex deployments for each update, risk of them getting out-of sync, harder debugging, more url's / entry points to the platform etc.

I would therefore suggest a page about the signupflow in the webshop, that links to the (unbranded) signupflow. As discussed the back button should be removed so that the user will use the browser back button and end up back on the webshop (municipality domain). No Forus logo anywhere in the provider's path :)

Figma: https://www.figma.com/file/fpYpPXqKqcQekCpYAI3hqU/Webshop-provider-page?node-id=1%3A483

![Me app - UPD.png](https://images.zenhubusercontent.com/5bc6fc7b86f3a678d497cf05/9a7fd8ee-fd4b-47af-8aab-ff75ca3ac738)

The button "aanmelden" links to the signupflow, that they have previewed within the municipality domain, no surprises there.

The button "inloggen" takes them to the general signupflow.

@maxvisser @danrminds  there's a couple different CR's in this one. Please analyse figma and this comment, and let me know if you guys think this is the way to go.

@maartenfv also curious to hear your thoughts.

**Comment by jamalv** [comment]
Note; if we make the slug for this page: aanbieder-aanmelden, then the url will (automatically) be: stadjerspas.nl/aanbieder-aanmelden, @maxvisser, right?

**Comment by danrminds** [comment]
Interesting, but this still does not cover the use case that a lot of providers received by mail (or email) the link to https://forus.io/provider , right?

**Comment by jamalv** [comment]
Yes, that's definitely right

**Comment by jamalv** [comment]
That one's a bit more complex, if @GerbenBosschieter approves I would like to implement https://github.com/teamforus/general/issues/71 as a solution to that. It will impact current providers, though. So that's something to consider.

Another solution would be to update that page in another way, for example by doing the same as suggested above, but then on our own site as wel;

<details><summary>suggested design</summary>

![Me app - UPD-home](https://user-images.githubusercontent.com/30194799/99651328-ba889780-2a56-11eb-81fd-cbedfa2ce700.png)


</details>

**Comment by maxvisser** [comment]
Not sure who will now make the IP and when it should be done.

**Comment by maxvisser** [comment]
Does this need to be part of release 17?

**Comment by danrminds** [comment]
Reviewed design

**Comment by jamalv** [comment]
I've put a checkbox with the concept @maxvisser could you review feasiblity? @linda-90 will review text. And maybe @maartenfv also wants to review this solution?

**Comment by jamalv** [comment]
When text review is done a final design review can be done and a master page can be created, added to the figma library and handed of to developers

**Comment by maxvisser** [comment]
Apart from the whole URL idea proposed in the stickies I see no issues.

**Comment by maxvisser** [comment]
I propose to fix that issue with forus website; If you login on forus.io we will show the Sponsor/validator/provider options

**Comment by maxvisser** [comment]
if you go to forus.io/sponsor you will get the login screen (with the open QR) button

**Comment by maxvisser** [comment]
I would split this epic up in three different development tasks:
1. Implementing the page on the webshop
2. Removing landing pages and implementing new login / register page landing page (can impact current landing pages!)
3. Implementing a login state for forus.io website with the choice between the three dashboards/roles

**Comment by jamalv** [comment]
I agree with max; first iteration of the provider page can even have the login button (top right) out of scope; as that makes it more complicated, would be nice to add that as part of point 2.

@danrminds could you plan this in?

**Comment by maartenfv** [comment]
I agree with solution. As in screenshot. Let's make it and show Groningen for review.
