### ISSUE TITLE
Improvement of ordering a physical card

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/general#525]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
- Groningen

**Note:** This change was requested after acceptance testing with stakeholders of project 100
**Requirement:** E5

### Change description
Ordering a physical card is incompleet. Really important information for the user is missing, after filling in all address information the user gets an confirmation that the card is send. We should add the following information:
- What address is the card sent to?
- How long will it take before they receive the card?
- Who do they call if they want to know about their order? Municipality doesn't have this information and citizens will not contact Forus. 

It's really important the give the user some information about the order.

For example, what if the users fills in their address information and clicks confirms but has a feeling that they gave the wrong information? They can not check this information about the order anywhere. So there is a change they are just going to order it again.

**Comment by maxvisser** [comment]
adding confirmation mail seems like scope small;

**Comment by maxvisser** [comment]
Text for mail is needed and which data needs to be included (to plan this issue.)

**Comment by SjoerdHilhorst** [comment]
https://github.com/teamforus/implementation/issues/513

**Comment by jamalv** [comment]
What address is the card sent to?

- email and modal have been updated (will be released monday)
- How long will it take before they receive the card?

<img width="729" alt="Screenshot 2020-11-14 at 14 02 50" src="https://user-images.githubusercontent.com/30194799/99147540-28614780-2682-11eb-8ff5-2c80efffdd96.png">

<img width="813" alt="Screenshot 2020-11-14 at 14 03 10" src="https://user-images.githubusercontent.com/30194799/99147535-24cdc080-2682-11eb-9a3b-733c569af47c.png">





Who do they call if they want to know about their order? Municipality doesn't have this information and citizens will not contact Forus.

- contact details of municipality are included in mail (screenshot not correct because of demo data in dev)

**Comment by maartenfv** [comment]
We fill in the KCC contact info so the municipality will receive the question first. If they do need more technical info the municipality will contact Forus support. @GerbenBosschieter please check if you see complications. If so please note them her so we van fix them.

**Comment by maartenfv** [comment]
I have re-planned this issue for sprint 47+48.

**Comment by maartenfv** [comment]
@maxvisser please check after Gerben has responded. We need to make sure we have the right contact info before this goes live.

**Comment by GerbenBosschieter** [comment]
@maartenfv  Don't see any complications

**Comment by jamalv** [comment]
@maartenfv it's organisation details, they can fill it in themselves, this screenshot was from dev.

**Comment by jamalv** [comment]
no dev needed

**Comment by maxvisser** [comment]
Implemented this morning release v0.16.0
