### ISSUE TITLE
Is it clear where the citizen "Early birds" will land when activating their account?

### ISSUE THREAD

**Issue by maartenfv** [teamforus/general#567]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
- Gemeente Groningen, 

### Change description
  Currently, it is unclear for the projectgroup:
  1. which functionalities will become available after the citizen has applied with DigiD. 
  2. How the citizen will be received in their account. 

Have we considered these points? @maxvisser @jamalv 

**Questions** 

1. What can the early birds do?
    - Can they order a physical card?
    - Can they download the Me app?
    - Can they connect the old card?
    -  etc.

 2.  How are they informed (within the system) about their options and the need to use the old system?
     -  Will there be some welcome information?
     -  Will they be informed on the page on the date of the switch?

 3. Considerations:
     - Can we hide the voucher until the actual live date in January? to prevent QR confusion.
     - Can we hide the order physical card button? to prevent dead ends
     - Can we hide the download me app button?
     - etc.

In general, we need to make sure they are not proceeding with using any functionality we do not want them to and prevent dead ends. Also, we need to prevent problems with support.

**Comment by maxvisser** [comment]
We could create a test voucher on production. Currently there are no limitations. From our end we have no special early birds information

**Comment by maartenfv** [comment]
PVA is here: https://docs.google.com/document/d/1F6qXgyCHYOYuJO_STusnKfTpIi0uuvG1-_tu7MIdjts/edit# but seems out dated?

**Comment by maartenfv** [comment]
Problem is that there are is nothing to order yet. so its a dead end

**Comment by jamalv** [comment]
> PVA is here: [docs.google.com/document/d/1F6qXgyCHYOYuJO_STusnKfTpIi0uuvG1-_tu7MIdjts/edit#](https://docs.google.com/document/d/1F6qXgyCHYOYuJO_STusnKfTpIi0uuvG1-_tu7MIdjts/edit#) but seems out dated?

As far as I am aware there have been no changes to the PVA. Also not aware of any changes since 25-09 (https://github.com/teamforus/implementation/issues/346#issuecomment-698933515) 

The open actions are: 
* Add one or two shops and actions 
* Train the shopkeepers in how to use the system. 

I would be a proponent of sticking to the original plan and to not make any last-minute changes; the risks of other directions are in the PVA.

The only dependancy still open afaik is the latest version of the Me app that supports actions. The app for android is currently live. The iOS version is still in review and should be released any day now.

**Comment by maxvisser** [comment]
Not applicable anymore
