### ISSUE TITLE
Overview page for Sponsor Dashboard

### ISSUE THREAD

**Issue by maartenfv** [teamforus/general#665]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
- Maarten

### Change description
- The provider dashboard has an overview page that is going to production. Can we make one for Sponsor as well? I think this will greatly improve the UX as users will have a place to start/"home".

**Comment by jamalv** [comment]
Agreed. We should first decide what's the strongest usecase here.

For the provider it was:
- Trigger them to start creating actions (instead of going trough the menu)
- Trigger them to apply for funds if they haven't already
- Help them understand that this is where they can see financial info
- Trigger them to add employees

I think for the sponsor we'd need to brainstorm a bit what's the most desirable info.

**Comment by maartenfv** [comment]
Can we get an estimate for the scope for this issue?

**Comment by maxvisser** [comment]
currently can't really give a good estimation as its not clear what is on the page.

**Comment by jamalv** [comment]
@maartenfv any ideas what would be the most relevant info for a sponsor when they open their account? where to link to and what data to show?

**Comment by maartenfv** [comment]
- Aantal actieve fondsen
- Nieuw fonds starten
- Totaal uitgegeven bedrag
- Aantal aanvragers per fonds
- Aantal aanbieders per fonds

**Comment by maartenfv** [comment]
@linda-90 Could we discuss this issue to plan making a design?

**Comment by linda-90** [comment]
Design (WIP): https://www.figma.com/file/bfp2Unid2vBQpJ3vxXTJzv/Sponsor-dashboard-overview-page?node-id=0%3A1&viewport=-1465%2C414%2C0.603611409664154

**Comment by linda-90** [comment]
Information:
- Number of active funds
- Aantal toekenningen
- Transactions
- Employees
