### ISSUE TITLE
Page title should match implementation.

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#727]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
Forus

### Change description
Right now the page title for webshops displays “Forus” this is sloppy and should be something more matching. E.g. “Stadjerspas”

![3CB37A95-23B3-477C-BF1C-B0DB0C792EE5](https://user-images.githubusercontent.com/30194799/103922414-ff09e880-5113-11eb-8951-323e6a297d49.jpeg)

**Comment by maxvisser** [comment]
Good one. We do have this its Groningen webshop ;) why its not working there is because angular replaces it on loading the page. you can see it happening when you load the site..
![image](https://user-images.githubusercontent.com/10818702/103927056-1350e400-511a-11eb-9851-4ca385ac744a.png)


Proposal is to change it to 'Laden...' if its not possible to fix it for all implementations

**Comment by maxvisser** [comment]
scope for my quickfix is small. maybe @dev-rminds knows some alternative.

**Comment by maxvisser** [comment]
Proposal to add these titles to env file
