### ISSUE TITLE
Make payments without bunq using SEPA export

### ISSUE THREAD

**Issue by maartenfv** [teamforus/general#818]
We currently are dependant on bunq. We need to make sure the system will work without this dependency. Therefor we will design a SEPA payment function.

**Comment by maartenfv** [comment]
Meer over SEPA: https://www.sepa.nl/sepa-introductie/

**Comment by maartenfv** [comment]
Data formats according to ING: https://www.ing.nl/zakelijk/betalen/betalingen-doen/bestandsformaten/index.html

**Comment by jamalv** [comment]
Suggested user stories: 

"As a sponsor I would like to export (pending) transactions in a SEPA format so that I can load the transactions in a financial system of my choosing, to perform the transactions" (must)
"As a sponsor I would like to change the status of transactions that I have paid from outside the system from "pending" to "succes" (should)

**Comment by maartenfv** [comment]
https://www.moneybird.nl/blog/moneybird-neemt-geen-psd2-voor-bankkoppelingen/

**Comment by maartenfv** [comment]
https://myponto.com/nl

**Comment by maxvisser** [comment]
interessant aan moneybird is 'inlezen' banktransacties -> wat gaat eruit 
linken aan 'facturen' openstaande betalingen;

concept kan dus zijn:
gemeente bouwt in Forus bulktransacties per aanbieder met meerdere kleinere transacties 'facturen'.
bijv scapino 10k van 100x €100 transacties
Bulk transactie krijgt een unieke code en bedrag. Wanneer gemeente zijn rekening data importeert (of dat wij dit uitlezen via een lichte bankkoppeling zoals moneybird) kun je alle kleinere transacties van 100 euro op voltooid zetten.

**Comment by jamalv** [comment]
Discussed with max; we came up with the following:

1. We can start with an MVP for the export. At the transactions screen when clicking export, you will get a choice between CSV and SEPA. If you click sepa the export will be formatted following the standards, so that you can pay in another system.

2. On top of this functionality there's plenty other stuff to build to make it better, for example payment status changes (quite important when actually using this functionality). Initially we can leave that out of scope and start with the first part, but still we'd need a (written/figma) proposal for this. Basic idea to start with is showing export status (yes/no).

1. could be done by sjoerd, 2. by alex?
