### ISSUE TITLE
Unify the organisation settings into a single menu

### ISSUE THREAD

**Issue by maartenfv** [teamforus/general#909]
![image](https://user-images.githubusercontent.com/30211022/171629304-bc773c77-9ccd-4cee-8109-6a2d205848b3.png)

![image](https://user-images.githubusercontent.com/30211022/171629361-56ff200f-8402-407a-bf98-e4eb575fff7c.png)

Currently there are three places (at least) to change organisational settings. This is unclear. Need to make a single clear menu.

**Comment by maartenfv** [comment]
@lexlog @GerbenBosschieter Can we do this?

**Comment by maartenfv** [comment]
@sashooa You had an idea about this? Can you dicuss this with @lexlog (if you have time).

**Comment by GerbenBosschieter** [comment]
We could if we want to. But I do recall a conversation with Valentin that he would like to use this location for some other purposes. Not sure what it was

**Comment by sashooa** [comment]
Link to the Figma file: https://www.figma.com/file/bG8kn0xyaPXZVCSijfnzAA/Improve-the-side-menu-in-the-user-dashboard-912

**Comment by lexlog** [comment]
refinement notes:
@dev-rminds proposed - we can move sessions and notifications menu items to dropdown list in the right upper corner

there was also something about the bell - could someone remind? and something else?
@sashooa @GerbenBosschieter @dev-rminds

**Comment by lexlog** [comment]
- @dev-rminds propose to make "role chooser" configurable per organization
- @RobinMeles @GerbenBosschieter check current flags for the roles ( as a sponsor as provider etc) and check if they are useful
- @GerbenBosschieter @dev-rminds @lexlog putting organization items to one place is not very ux friendly also, because its not personal configuration, but dashboard configuration
-

**Comment by sashooa** [comment]
> refinement notes: @dev-rminds proposed - we can move sessions and notifications menu items to a drop-down list in the right upper corner two icons (help icon ) one below other and change banner
> 
> @lexlog create different issue for that

https://www.figma.com/file/Fx3s4hFDIfTkHtm5SGhlD7/Update-sidebar-menu-and-add-helpcentrum-icon-%7C-909?node-id=1549%3A6144 here's the Design

**Comment by GerbenBosschieter** [comment]
So I've checked what flags we currently have. And its about these three:

- is_sponsor
- is_provider
- is_validator

Not sure where the **is_sponsor** and **is_provider** is used for. But for certainly I can say that **is_validator** is being used for external validator (something we are currently not using)

I am not sure if we could use this configuration because its on organization level and not identity_adress level. We could only use it if we could use this flag for all employees of the organization.

**Comment by lexlog** [comment]
refinement note

@GerbenBosschieter check, while using sign-up flow, is there are a flag "is_sponsor" when using signup as an organization

**Comment by ateamcms** [comment]
https://github.com/teamforus/forus-frontend/pull/2252
